
package uy.edu.fing.volandouy.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "detallesReservaServiceService", targetNamespace = "http://volandouy.fing.edu.uy/webServices/", wsdlLocation = "http://localhost:9130/detallesReservaService?wsdl")
public class DetallesReservaServiceService
    extends Service
{

    private final static URL DETALLESRESERVASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DETALLESRESERVASERVICESERVICE_EXCEPTION;
    private final static QName DETALLESRESERVASERVICESERVICE_QNAME = new QName("http://volandouy.fing.edu.uy/webServices/", "detallesReservaServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9130/detallesReservaService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DETALLESRESERVASERVICESERVICE_WSDL_LOCATION = url;
        DETALLESRESERVASERVICESERVICE_EXCEPTION = e;
    }

    public DetallesReservaServiceService() {
        super(__getWsdlLocation(), DETALLESRESERVASERVICESERVICE_QNAME);
    }

    public DetallesReservaServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DETALLESRESERVASERVICESERVICE_QNAME, features);
    }

    public DetallesReservaServiceService(URL wsdlLocation) {
        super(wsdlLocation, DETALLESRESERVASERVICESERVICE_QNAME);
    }

    public DetallesReservaServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DETALLESRESERVASERVICESERVICE_QNAME, features);
    }

    public DetallesReservaServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DetallesReservaServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DetallesReservaService
     */
    @WebEndpoint(name = "detallesReservaServicePort")
    public DetallesReservaService getDetallesReservaServicePort() {
        return super.getPort(new QName("http://volandouy.fing.edu.uy/webServices/", "detallesReservaServicePort"), DetallesReservaService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DetallesReservaService
     */
    @WebEndpoint(name = "detallesReservaServicePort")
    public DetallesReservaService getDetallesReservaServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://volandouy.fing.edu.uy/webServices/", "detallesReservaServicePort"), DetallesReservaService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DETALLESRESERVASERVICESERVICE_EXCEPTION!= null) {
            throw DETALLESRESERVASERVICESERVICE_EXCEPTION;
        }
        return DETALLESRESERVASERVICESERVICE_WSDL_LOCATION;
    }

}
