
package uy.edu.fing.volandouy.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ListaPaqueteServiceService", targetNamespace = "http://volandouy.fing.edu.uy/webServices/", wsdlLocation = "http://localhost:9130/ListaPaqueteService?wsdl")
public class ListaPaqueteServiceService
    extends Service
{

    private final static URL LISTAPAQUETESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException LISTAPAQUETESERVICESERVICE_EXCEPTION;
    private final static QName LISTAPAQUETESERVICESERVICE_QNAME = new QName("http://volandouy.fing.edu.uy/webServices/", "ListaPaqueteServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9130/ListaPaqueteService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LISTAPAQUETESERVICESERVICE_WSDL_LOCATION = url;
        LISTAPAQUETESERVICESERVICE_EXCEPTION = e;
    }

    public ListaPaqueteServiceService() {
        super(__getWsdlLocation(), LISTAPAQUETESERVICESERVICE_QNAME);
    }

    public ListaPaqueteServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LISTAPAQUETESERVICESERVICE_QNAME, features);
    }

    public ListaPaqueteServiceService(URL wsdlLocation) {
        super(wsdlLocation, LISTAPAQUETESERVICESERVICE_QNAME);
    }

    public ListaPaqueteServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LISTAPAQUETESERVICESERVICE_QNAME, features);
    }

    public ListaPaqueteServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ListaPaqueteServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ListaPaqueteService
     */
    @WebEndpoint(name = "ListaPaqueteServicePort")
    public ListaPaqueteService getListaPaqueteServicePort() {
        return super.getPort(new QName("http://volandouy.fing.edu.uy/webServices/", "ListaPaqueteServicePort"), ListaPaqueteService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ListaPaqueteService
     */
    @WebEndpoint(name = "ListaPaqueteServicePort")
    public ListaPaqueteService getListaPaqueteServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://volandouy.fing.edu.uy/webServices/", "ListaPaqueteServicePort"), ListaPaqueteService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LISTAPAQUETESERVICESERVICE_EXCEPTION!= null) {
            throw LISTAPAQUETESERVICESERVICE_EXCEPTION;
        }
        return LISTAPAQUETESERVICESERVICE_WSDL_LOCATION;
    }

}
