
package uy.edu.fing.volandouy.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "LoginServiceService", targetNamespace = "http://volandouy.fing.edu.uy/webServices/", wsdlLocation = "http://localhost:9130/LoginService?wsdl")
public class LoginServiceService
    extends Service
{

    private final static URL LOGINSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException LOGINSERVICESERVICE_EXCEPTION;
    private final static QName LOGINSERVICESERVICE_QNAME = new QName("http://volandouy.fing.edu.uy/webServices/", "LoginServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9130/LoginService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOGINSERVICESERVICE_WSDL_LOCATION = url;
        LOGINSERVICESERVICE_EXCEPTION = e;
    }

    public LoginServiceService() {
        super(__getWsdlLocation(), LOGINSERVICESERVICE_QNAME);
    }

    public LoginServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOGINSERVICESERVICE_QNAME, features);
    }

    public LoginServiceService(URL wsdlLocation) {
        super(wsdlLocation, LOGINSERVICESERVICE_QNAME);
    }

    public LoginServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOGINSERVICESERVICE_QNAME, features);
    }

    public LoginServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoginService
     */
    @WebEndpoint(name = "LoginServicePort")
    public LoginService getLoginServicePort() {
        return super.getPort(new QName("http://volandouy.fing.edu.uy/webServices/", "LoginServicePort"), LoginService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginService
     */
    @WebEndpoint(name = "LoginServicePort")
    public LoginService getLoginServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://volandouy.fing.edu.uy/webServices/", "LoginServicePort"), LoginService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOGINSERVICESERVICE_EXCEPTION!= null) {
            throw LOGINSERVICESERVICE_EXCEPTION;
        }
        return LOGINSERVICESERVICE_WSDL_LOCATION;
    }

}
