
package uy.edu.fing.volandouy.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "PaqueteControllerServiceService", targetNamespace = "http://volandouy.fing.edu.uy/webServices/", wsdlLocation = "http://localhost:9130/PaqueteControllerService?wsdl")
public class PaqueteControllerServiceService
    extends Service
{

    private final static URL PAQUETECONTROLLERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PAQUETECONTROLLERSERVICESERVICE_EXCEPTION;
    private final static QName PAQUETECONTROLLERSERVICESERVICE_QNAME = new QName("http://volandouy.fing.edu.uy/webServices/", "PaqueteControllerServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9130/PaqueteControllerService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAQUETECONTROLLERSERVICESERVICE_WSDL_LOCATION = url;
        PAQUETECONTROLLERSERVICESERVICE_EXCEPTION = e;
    }

    public PaqueteControllerServiceService() {
        super(__getWsdlLocation(), PAQUETECONTROLLERSERVICESERVICE_QNAME);
    }

    public PaqueteControllerServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAQUETECONTROLLERSERVICESERVICE_QNAME, features);
    }

    public PaqueteControllerServiceService(URL wsdlLocation) {
        super(wsdlLocation, PAQUETECONTROLLERSERVICESERVICE_QNAME);
    }

    public PaqueteControllerServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAQUETECONTROLLERSERVICESERVICE_QNAME, features);
    }

    public PaqueteControllerServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaqueteControllerServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PaqueteControllerService
     */
    @WebEndpoint(name = "PaqueteControllerServicePort")
    public PaqueteControllerService getPaqueteControllerServicePort() {
        return super.getPort(new QName("http://volandouy.fing.edu.uy/webServices/", "PaqueteControllerServicePort"), PaqueteControllerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaqueteControllerService
     */
    @WebEndpoint(name = "PaqueteControllerServicePort")
    public PaqueteControllerService getPaqueteControllerServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://volandouy.fing.edu.uy/webServices/", "PaqueteControllerServicePort"), PaqueteControllerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAQUETECONTROLLERSERVICESERVICE_EXCEPTION!= null) {
            throw PAQUETECONTROLLERSERVICESERVICE_EXCEPTION;
        }
        return PAQUETECONTROLLERSERVICESERVICE_WSDL_LOCATION;
    }

}
