
package uy.edu.fing.volandouy.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "VueloControllerServiceService", targetNamespace = "http://volandouy.fing.edu.uy/webServices/", wsdlLocation = "http://localhost:9130/VueloControllerService?wsdl")
public class VueloControllerServiceService
    extends Service
{

    private final static URL VUELOCONTROLLERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException VUELOCONTROLLERSERVICESERVICE_EXCEPTION;
    private final static QName VUELOCONTROLLERSERVICESERVICE_QNAME = new QName("http://volandouy.fing.edu.uy/webServices/", "VueloControllerServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9130/VueloControllerService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VUELOCONTROLLERSERVICESERVICE_WSDL_LOCATION = url;
        VUELOCONTROLLERSERVICESERVICE_EXCEPTION = e;
    }

    public VueloControllerServiceService() {
        super(__getWsdlLocation(), VUELOCONTROLLERSERVICESERVICE_QNAME);
    }

    public VueloControllerServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VUELOCONTROLLERSERVICESERVICE_QNAME, features);
    }

    public VueloControllerServiceService(URL wsdlLocation) {
        super(wsdlLocation, VUELOCONTROLLERSERVICESERVICE_QNAME);
    }

    public VueloControllerServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VUELOCONTROLLERSERVICESERVICE_QNAME, features);
    }

    public VueloControllerServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VueloControllerServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VueloControllerService
     */
    @WebEndpoint(name = "VueloControllerServicePort")
    public VueloControllerService getVueloControllerServicePort() {
        return super.getPort(new QName("http://volandouy.fing.edu.uy/webServices/", "VueloControllerServicePort"), VueloControllerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VueloControllerService
     */
    @WebEndpoint(name = "VueloControllerServicePort")
    public VueloControllerService getVueloControllerServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://volandouy.fing.edu.uy/webServices/", "VueloControllerServicePort"), VueloControllerService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VUELOCONTROLLERSERVICESERVICE_EXCEPTION!= null) {
            throw VUELOCONTROLLERSERVICESERVICE_EXCEPTION;
        }
        return VUELOCONTROLLERSERVICESERVICE_WSDL_LOCATION;
    }

}
