
package uy.edu.fing.volandouy.webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ImagenesServiceService", targetNamespace = "http://volandouy.fing.edu.uy/webServices/", wsdlLocation = "http://localhost:9130/ImagenesService?wsdl")
public class ImagenesServiceService
    extends Service
{

    private final static URL IMAGENESSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException IMAGENESSERVICESERVICE_EXCEPTION;
    private final static QName IMAGENESSERVICESERVICE_QNAME = new QName("http://volandouy.fing.edu.uy/webServices/", "ImagenesServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9130/ImagenesService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMAGENESSERVICESERVICE_WSDL_LOCATION = url;
        IMAGENESSERVICESERVICE_EXCEPTION = e;
    }

    public ImagenesServiceService() {
        super(__getWsdlLocation(), IMAGENESSERVICESERVICE_QNAME);
    }

    public ImagenesServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMAGENESSERVICESERVICE_QNAME, features);
    }

    public ImagenesServiceService(URL wsdlLocation) {
        super(wsdlLocation, IMAGENESSERVICESERVICE_QNAME);
    }

    public ImagenesServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMAGENESSERVICESERVICE_QNAME, features);
    }

    public ImagenesServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImagenesServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ImagenesService
     */
    @WebEndpoint(name = "ImagenesServicePort")
    public ImagenesService getImagenesServicePort() {
        return super.getPort(new QName("http://volandouy.fing.edu.uy/webServices/", "ImagenesServicePort"), ImagenesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImagenesService
     */
    @WebEndpoint(name = "ImagenesServicePort")
    public ImagenesService getImagenesServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://volandouy.fing.edu.uy/webServices/", "ImagenesServicePort"), ImagenesService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMAGENESSERVICESERVICE_EXCEPTION!= null) {
            throw IMAGENESSERVICESERVICE_EXCEPTION;
        }
        return IMAGENESSERVICESERVICE_WSDL_LOCATION;
    }

}
