
package uy.edu.fing.volandouy.webservices;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PaqueteControllerService", targetNamespace = "http://volandouy.fing.edu.uy/webServices/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaqueteControllerService {


    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://volandouy.fing.edu.uy/webServices/PaqueteControllerService/crearPaqueteDeRutaDeVueloRequest", output = "http://volandouy.fing.edu.uy/webServices/PaqueteControllerService/crearPaqueteDeRutaDeVueloResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://volandouy.fing.edu.uy/webServices/PaqueteControllerService/crearPaqueteDeRutaDeVuelo/Fault/Exception")
    })
    public void crearPaqueteDeRutaDeVuelo(
        @WebParam(name = "arg0", partName = "arg0")
        PaqueteDto arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://volandouy.fing.edu.uy/webServices/PaqueteControllerService/agregarRutaDeVueloAPaqueteRequest", output = "http://volandouy.fing.edu.uy/webServices/PaqueteControllerService/agregarRutaDeVueloAPaqueteResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://volandouy.fing.edu.uy/webServices/PaqueteControllerService/agregarRutaDeVueloAPaquete/Fault/Exception")
    })
    public void agregarRutaDeVueloAPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        ComercializaDto arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns uy.edu.fing.volandouy.webservices.PaqueteDto
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://volandouy.fing.edu.uy/webServices/PaqueteControllerService/buscarPaquetePorNombreRequest", output = "http://volandouy.fing.edu.uy/webServices/PaqueteControllerService/buscarPaquetePorNombreResponse")
    public PaqueteDto buscarPaquetePorNombre(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @Action(input = "http://volandouy.fing.edu.uy/webServices/PaqueteControllerService/comprarPaqueteRequest", output = "http://volandouy.fing.edu.uy/webServices/PaqueteControllerService/comprarPaqueteResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://volandouy.fing.edu.uy/webServices/PaqueteControllerService/comprarPaquete/Fault/Exception")
    })
    public void comprarPaquete(
        @WebParam(name = "arg0", partName = "arg0")
        CompraPaqueteDto arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns uy.edu.fing.volandouy.webservices.PaqueteList
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://volandouy.fing.edu.uy/webServices/PaqueteControllerService/listarPaquetesRequest", output = "http://volandouy.fing.edu.uy/webServices/PaqueteControllerService/listarPaquetesResponse")
    public PaqueteList listarPaquetes();

}
